---
# tasks file for vsftpd

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install vsftpd
  ansible.builtin.package:
    name: vsftpd

- name: Configure vsftpd
  ansible.builtin.template:
    src: vsftpd.conf.j2
    dest: "{{ vsftpd_configuration_file }}"
    owner: root
    group: root
    mode: "{{ vsftpd_configuration_file_mode }}"
  notify:
    - Restart vsftpd

- name: Start and enable vsftpd
  ansible.builtin.service:
    name: vsftpd
    state: started
    enabled: true

- name: Assert banner_email_file exists
  ansible.builtin.file:
    path: {{ vsftpd_banned_email_file }}
    state: directory
    owner: root
    group: root
    mode: '0700'
  when: vsftpd_deny_email_enable is true

