---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if port 21 is available
      ansible.builtin.wait_for:
        port: 21
        state: started
        timeout: 1
